### PR TITLE
Introduce BDD using Cucumber

### PR DESCRIPTION
**Pull request by dtitov**
Here I added [Cucumber](https://cucumber.io/) framework for bringing [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development) to our project. We can implement testing by writing scenarios using human-readable constructions like:
```gherkin
Feature: Authentication
  As a user I want to be able to authenticate against LocalEGA inbox

  Scenario: Authenticate against LocalEGA inbox
    Given I have username and password
    When I try to connect to the LocalEGA inbox via SFTP using these credentials
    Then the operation is successful
```
 Here's a sample (but still real) test of authentication:

[asciicast](https://asciinema.org/a/hS8nRm9FUKMqmRsTpKagENESd)

### CODE REVIEW

**Comment by dtitov** [comment]
Made it work on Jenkins: http://158.39.77.10/job/LocalEGA/73/console

**Comment by silverdaz** [comment]
Can you explain more about the "Allow password authentication" commit?

Because `"keyboard-interactive:pam"` is already password authentication...

**Comment by dtitov** [comment]
> Can you explain more about the "Allow password authentication" commit?
`keyboard-interactive:pam` is really interactive: you need **to type** the password to log in. And I'm logging in to the SFTP programmatically, so I can't type anything. Without enabling password authentication I simply can't automate SFTP login from Cucumber side.

> Do we need the maven stuff? Have you looked at some other ones?
Sure, we can try go for something else. But I have experience in Cucumber, so I decided to use it for now. It's Java-based - that's why I used Maven.

**Comment by silverdaz** [comment]
We decided to go away from a Java+MVN solution and now it sneaks in again. I'm not so fond of that, but if we _really_ need to do it, then so be it. However, I doubt it is really necessary.

As for the password, thanks for the obvious answer, but no, "no automation for logging-in" is exactly the reason to remove password. I have given some thoughts long time ago, and we decided to not have it.

So, no, I don't want to merge that part.

My suggestion to help the issue though, is to use an ssh-key. That's what I did on the terraform VMs. Generate an SSH key pair in your test, inject the public one at boot time and connect automatically using the private one. That's how I'd do it, and I would not open a hole by using password, just because it makes testing simpler.

**Comment by dtitov** [comment]
@silverdaz 
Regarding Maven: didn't know about it's history within LocalEGA. But I based this decision on our very early talk in Slack, when you told that the benefit of LocalEGA is modularity, which allows us to implement different parts of the system using different languages/technologies (you even gave an example of C-code in the project). So that's why Java appeared here. Fix me if I misunderstood you back then. But, anyway, it's not even a business logic of the application - it's just a test-suite.

Regarding password-auth. It's already in `master`, it came from another PR: https://github.com/NBISweden/LocalEGA/pull/134 Sorry, we didn't wait for you to commit such a small fix. Of course, you can remove it, but could you, please, previously explain what is the vulnerability itself? We anyway already have password-based authentication. It was interactive before and now I want to make it be non-interactive. How does exactly it compromise the system?

**Comment by dtitov** [comment]
@jhagberg, no problem. What should I use instead?

**Comment by silverdaz** [comment]
Go ahead and use Maven.

I would like to see the list of tests, not the tool that will do it.

It's a first step, I know, so go on now with the real tests.

**Comment by jhagberg** [comment]
Use something agnostic e.g nothing specific I think it can confuse.

**Comment by dtitov** [comment]
@jhagberg, there's a specific naming convention for package names: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

> Companies use their reversed Internet domain name to begin their package names—for example, com.example.mypackage for a package named mypackage created by a programmer at example.com.

So it's conventional to use reverse-domain semantic, I just was not sure which domain to pick. We can use something like `com.github.nbisweden.*` if you like it.

**Comment by nanjiangshu** [comment]
For authentication without password, you can use ssh-key authentication. 

I can also use simple bash script for testing procedures 
This is an example I have been writing
```
if [ "$operation" == "all" -o "$operation" == "bootstrap" ]; then
    echo "Generate configurations ..."
    docker run --rm -it -v ${rundir}/bootstrap:/ega nbis/ega:worker /ega/generate.sh
    if [ $isPause -eq 1 ];then pause; fi

    echo "Move configuration files to the right place ..."
    bootstrap/populate.sh
    if [ $isPause -eq 1 ];then pause; fi
fi


if [ "$operation" == "all" -o "$operation" == "dockerup" ]; then
    echo "Start docker containers ..."
    docker-compose up -d
    if [ $isPause -eq 1 ];then pause; fi
fi

if [ "$operation" == "all" -o "$operation" == "adduser" ]; then
    echo "Add a user with only password ..."
    username=myuser1
    userfile=bootstrap/private/cega/users/${username}.yml
    echo -e '---\npassword_hash: $1$mysalt$4YD3lRSUvRfoUFDEV4irl1' | sudo tee $userfile
    echo
    echo "Add a user with both password and ssh-key ..."
    username=myuser2
    userfile=bootstrap/private/cega/users/${username}.yml
    echo -e '---\npassword_hash: $1$mysalt$4YD3lRSUvRfoUFDEV4irl1\npubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+/orXTIDXpv0aC8ZRktZk9ScTz/19JZp/e66FTq4Bpq/dkrX78BBqovCatfW9YE2H1qYzaMRzGRIKWllOb+J/6uo2zsE0kCFKwrZIWE2OduWN/otPi6P/sn7MrtoBxGuuxJg5dr+fQzdtOqzv21v3wvJp/RifEa3dwOGMh7srzGUZIn/TAVf6hi9Pg71vcVuRu7bSMHsbonEzTF+w4+zJeboc4ZlesYvi4eM1eYCWEwBwXYwS/hPdZWy/zuYH4hdrbfr4F/MwY+lfhoKmbv11IrLos/5/Fd1oKj4evqVj9+3yqYZggfNjMjR09NTN9jD1yY4J7tpatNrHorabv/Vr dummy@bioshu.se' | sudo tee $userfile
    if [ $isPause -eq 1 ];then pause; fi
fi

if [ "$operation" == "all" -o "$operation" == "createdata" ]; then
    echo "create test data ..."
    if [ ! -d $path_orig_data ];then mkdir -p $path_orig_data; fi
    if [ ! -d $path_enc_data ];then mkdir -p $path_enc_data; fi
    if [ ! -s $path_orig_data/data-1K.txt ];then openssl rand -base64 750 > $path_orig_data/data-1K.txt; fi
    if [ ! -s $path_orig_data/data-1M.txt ];then openssl rand -base64 760000 > $path_orig_data/data-1M.txt; fi
    if [ ! -s $path_orig_data/data-1K.dat ];then dd if=/dev/urandom bs=1 count=1k > $path_orig_data/data-1K.dat ; fi
    if [ ! -s $path_orig_data/data-1M.dat ];then dd if=/dev/urandom bs=1 count=1M > $path_orig_data/data-1M.dat ; fi
    datafilelist="data-1K.txt data-1M.txt data-1K.dat data-1M.dat"
    for datafile in $datafilelist; do
        docker run -d --rm -it -v ${rundir}/:/ega nbis/ega:worker gpg --homedir /ega/bootstrap/private/gpg  -e -r ega@nbis.se -o /ega/test/encdata/${datafile}.enc /ega/test/origdata/${datafile}
    done

    if [ $isPause -eq 1 ];then pause; fi
fi

if [ "$operation" == "all" -o "$operation" == "uploaddata" ]; then
    echo "Upload data to SFTP ..."
    datafilelist="data-1K.txt.enc data-1M.txt.enc data-1K.dat.enc data-1M.dat.enc"
    for datafile in $datafilelist; do
        sftp -P 2222 -i ~/.ssh/dummy.key myuser2@localhost <<< $"put $path_enc_data/$datafile" 
    done
    if [ $isPause -eq 1 ];then pause; fi
fi


if [ "$operation" == "all" -o "$operation" == "ingest" ]; then
    if [ $isPause -eq 1 ];then pause; fi
fi
```

**Comment by jhagberg** [comment]
Yes you are right @dtitov then I think we should use nbis.se since we are mainly developing this under NBIS flag/name now. So we follow the same naming.

**Comment by dtitov** [comment]
@jhagberg, okay.

@nanjiangshu, alright then, I can go for a key authentication. It will just add more work to do. The only benefit of 'keyboard-interactive authentication' is possibility to request for more information then just a password (some secret, for example). But since we don't request anything, except password, currently they are the same (apart from fact that it just makes things more complicated from the CI perspective).

**Comment by jhagberg** [comment]
The goal for the sprint is to
* Dymtro find out decision information about Jenkins 
We want to get as much information as possible to later decide on what CI to use. This pull request should not be merged with master.

**Comment by jhagberg** [comment]
Please rename the branch to test/cucumber and we will use that as test to gather information to later decide on what CI to use.

**Pull request closed without merging**
