### PR TITLE
Add gosu permission deescalation

### PR DESCRIPTION
**Pull request by dtitov**
- keyserver
- worker
- vault

### CODE REVIEW

**Comment by silverdaz** [comment]
Can you fix the Travis (pr) error, though?

I see that:
```
ERROR: for ega-keys-swe1  Cannot start service keys-swe1: oci runtime error: container_linux.go:265: starting container process caused "exec: \"gosu\": executable file not found in $PATH"

Creating ega-vault-swe1

ERROR: for keys-swe1  Cannot start service keys-swe1: oci runtime error: container_linux.go:265: starting container process caused "exec: \"gosu\": executable file not found in $PATH"

Encountered errors while bringing up the project.

The command "docker-compose up -d ${DOCKER_CONTAINERS}" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by dtitov** [comment]
@silverdaz This is because the image was changed and I need to push it to Docker Hub. But I didn't want to do it before the review. But not, since it looks fine, I will push the image and restart the Travis build to see if it's fine.

**Comment by silverdaz** [comment]
Upload them, and I'll merge once Travis passes.

I'm not too worried if Travis fails, after the upload. We can revert easily.
But there is of course the solution to temporarily rename the images, if you prefer.

**Comment by dtitov** [comment]
Done!

**Pull request merged**
