### PR TITLE
Feature/entrypoints

### PR DESCRIPTION
**Pull request by silverdaz**
Adding the entrypoints to the docker images.

Moreover, adding a few ENV variables in the entrypoint script to remove hard-coded settings.

This solves issue #182 in another way.
The directory structure remains unchanged, and `pip install` is run _after_ `git clone && git checkout <commit>`

### CODE REVIEW

**Comment by silverdaz** [comment]
I stand corrected, it's issue #183.

**Comment by silverdaz** [comment]
@dtitov : I added you as a reviewer, so you can have a look at the tests.
It apparently does not manage to log onto the inbox.
Maybe a miss on my side, but maybe a misconfiguration in the testsuite.

By the way, did you create this external file, that tests refer too, so that we can update it and not look into the tests themselves?

**Comment by dtitov** [comment]
@silverdaz, not yet. We should add this task to the next sprint, I guess.

I briefly looked into logs and looks like you renamed some of the images, so test-code can't find some containers by their old names. 

Can this wait until Monday?

**Comment by silverdaz** [comment]
Sure!

But you mean the containers or the images?
I didn't change the containers' names. But true that some new images have been introduced (and the old ones are still there, though different)

Why does it even matter? I don't understand why it would break, since we introduced makefiles that take care of those names.

**Comment by dtitov** [comment]
OK, I was too curious about the issues, so I've taken a deeper look and found a couple of problems (and fixed them).

The first one is, as I mentioned, with image names, at least with one: vault containers started to use `nbisweden/ega-vault` instead of `nbisweden/ega-common`, as before. So I had to rename it correspondently in place, where I access such container via Docker API.

But there was also another, more complicated issue. For some operations (like files encryption) I dynamically spawn temporary Docker containers (workers) to execute some commands within. I previously it "just worked", but after this patch, I need to provide 3 additional env-variables in order for the container to be created:
- MQ_INSTANCE
- KEYSERVER_HOST
- KEYSERVER_PORT

So now I'm providing these values.

P.S. Pushing the fixes to this branch, let's see if it works.

**Comment by dtitov** [comment]
OK, we are all green now, but if you don't mind, I'd still like to wait until Monday, so I can read the code more carefully to get better understanding :)

**Pull request merged**
