### PR TITLE
Adjusting docker-compose

### PR DESCRIPTION
**Pull request by silverdaz**
This is a version of the docker approach that creates 3 volumes, uses less images and no pyenv.
A few required settings are also removed.

That corresponds more to the terraform version.

### CODE REVIEW

**Comment by nanjiangshu** [comment]
at the HEAD #02ae2da, I got some problems to even start the containers

The status of the containers are listed below

```
$ docker-compose ps
     Name                   Command               State                         Ports                     
----------------------------------------------------------------------------------------------------------
ega_connectors   connectors.sh                    Exit 0                                                  
ega_db           db.sh                            Up       0.0.0.0:5050->5050/tcp, 0.0.0.0:5051->5051/tcp,
                                                           5432/tcp                                       
ega_frontend     frontend.sh                      Exit 2                                                  
ega_inbox        inbox.sh                         Up       0.0.0.0:2222->22/tcp                           
ega_keys         keys.sh                          Up                                                      
ega_mq           docker-entrypoint.sh rabbi ...   Up       15671/tcp, 0.0.0.0:15672->15672/tcp, 25672/tcp,
                                                           4369/tcp, 5671/tcp, 5672/tcp                   
ega_vault        vault.sh                         Exit 1                                                  
ega_worker_1     worker.sh                        Exit 1   
```

The `frontend` exit with some strange message with database errors. While the same postgrel setting works in the master branch.

```
frontend_1    | [ frontend ][DEBUG ] (L142) Template folder: /usr/lib/python3.6/site-packages/lega/conf/templates
frontend_1    | [ frontend ][ INFO ] (L147) Registering routes
frontend_1    | [ frontend ][ INFO ] (L153) Setting up callbacks
frontend_1    | [ frontend ][ INFO ] (L161) Starting the real deal on <ega-frontend:9000>
frontend_1    | Connection error to the Postgres database
frontend_1    |  could not translate host name "ega-db" to address: Name or service not known
```
See like the problem is from the connectors when I checked the logs of connectors

```
connectors_1  |   File "/root/ega/lega/utils/amqp.py", line 50, in get_connection
connectors_1  |     return pika.BlockingConnection( pika.ConnectionParameters(**params) )
connectors_1  |   File "/usr/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 339, in __init__
connectors_1  |     self._process_io_for_connection_setup()
connectors_1  |   File "/usr/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 378, in _process_io_for_connection_setup
connectors_1  |     self._open_error_result.value.error_text)
connectors_1  | pika.exceptions.AMQPConnectionError: [Errno -2] Name or service not known
connectors_1  | Traceback (most recent call last):
connectors_1  |   File "/usr/bin/ega-connect", line 11, in <module>
connectors_1  |     load_entry_point('lega', 'console_scripts', 'ega-connect')()
connectors_1  |   File "/root/ega/lega/connect.py", line 87, in connect
connectors_1  |     _connect(*connection, **kwargs)
connectors_1  |   File "/root/ega/lega/connect.py", line 41, in _connect
connectors_1  |     from_connection = get_connection(from_domain)
connectors_1  |   File "/root/ega/lega/utils/amqp.py", line 50, in get_connection
connectors_1  |     return pika.BlockingConnection( pika.ConnectionParameters(**params) )
connectors_1  |   File "/usr/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 339, in __init__
connectors_1  |     self._process_io_for_connection_setup()
connectors_1  |   File "/usr/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 378, in _process_io_for_connection_setup
connectors_1  |     self._open_error_result.value.error_text)
connectors_1  | pika.exceptions.AMQPConnectionError: [Errno -2] Name or service not known
connectors_1  | Traceback (most recent call last):
connectors_1  |   File "/usr/bin/ega-connect", line 11, in <module>
connectors_1  |     load_entry_point('lega', 'console_scripts', 'ega-connect')()
connectors_1  |   File "/root/ega/lega/connect.py", line 87, in connect
connectors_1  |     _connect(*connection, **kwargs)
connectors_1  |   File "/root/ega/lega/connect.py", line 41, in _connect
connectors_1  |     from_connection = get_connection(from_domain)
connectors_1  |   File "/root/ega/lega/utils/amqp.py", line 50, in get_connection
connectors_1  |     return pika.BlockingConnection( pika.ConnectionParameters(**params) )
connectors_1  |   File "/usr/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 339, in __init__
connectors_1  |     self._process_io_for_connection_setup()
connectors_1  |   File "/usr/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 378, in _process_io_for_connection_setup
connectors_1  |     self._open_error_result.value.error_text)
connectors_1  | pika.exceptions.AMQPConnectionError: [Errno -2] Name or service not known
```

**Comment by silverdaz** [comment]
Well, the name are ega_something, not ega-something.

So, in your conf file, that should be reflected accordingly

**Comment by nanjiangshu** [comment]
Didn't realize that you have made these changes. I have changed the ini file and re-run the testing now

**Comment by nanjiangshu** [comment]
SFTP user creation with the following command succeeded

```
docker-compose exec frontend ega-publisher inbox --broker 'cega.broker' --routing 'sweden.user' 'test1' 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6xZlwFv9yWTBxQPHQcwUMETO8JO+qY55rQO8LPs6ncqidUX2BBjd92KHTOyLLZMG3fyWDKs/Tjm9mPHs+xEMBPpaQ2/xjy745m+cm1tEAiOo/hL4lemKtLuVO1aOZlN5eY2MeggRPUh1HlNBeAbOiDa8DQ0jPPlKrV//9ULXFNHeGTDYRrbBsWpVd5IPIW2dzfYnJF5j+xdQKr5Hvmvk+TmzcEIVOlkkRvX/+DBz405gVVrbO4aH4a9G+/9OuZauCkQNg6hXwBv+XetpXOoLKK9eyGrGTRLaeE3NqBgonmhquFM4wIh0JiR3nTD8FW/R8hCQlQQ0v5Nkd66IX3XNd nanjiang.shu@dbb.su.se' '$1$mysalt$4YD3lRSUvRfoUFDEV4irl1' 
```

However, data uploading failed with "permission denied" error
```
Uploading README.md to /README.md
remote open("/README.md"): Permission denied
```

The inbox `/ega/inbox` in the container `ega_inbox` is not mounted to the INBOX set in the `.env` file. When I checked the settings in the docker-compose.yml file, I find for the inbox volume, it is defined like this 

https://github.com/NBISweden/LocalEGA/blob/docker/docker/docker-compose.yml#48

shouldn't it be as 

`${INBOX}:/ega/inbox`

The volumes for `vault` and `staging` are defined also like this

https://github.com/NBISweden/LocalEGA/blob/docker/docker/docker-compose.yml#84
https://github.com/NBISweden/LocalEGA/blob/docker/docker/docker-compose.yml#85

**Comment by nanjiangshu** [comment]
It seems the problem is that `userid/inbox` folder does not exist according to the logs of inbox

```
inbox_1       | Accepted keyboard-interactive/pam for test1 from 172.20.0.1 port 49210 ssh2
inbox_1       | chdir to "/inbox" failed: No such file or directory [postauth]
```
When I go to inside of the `ega_inbox` container. I noticed that the `/ega/skel` folder does have the `inbox` subfolder, not not for the user folder, e.g.

```
|-- inbox
|   |-- nanjiang
|   |-- test
|   `-- test1
`-- skel
    `-- inbox
```

**Comment by silverdaz** [comment]
Indeed. There was a problem with the `setgid`. We don't mount the inbox and vault area, we create volumes.

**Comment by silverdaz** [comment]
You probably need to remake the images too

**Comment by nanjiangshu** [comment]
I rebuilt images and it is the same situation that sftp user do not have the permission to upload the date 

I'll try it again by deleting old images and force rebuilt images again.

Indeed, it would be better if one can run force rebuilding by 

`make -B`

**Comment by nanjiangshu** [comment]
I deleted all images and re-built the images and then started all containers. However, 
I still got permission error when trying to upload files to the sftp server. 
`/inbox` does not exist.

**Comment by nanjiangshu** [comment]
It is wired. I do see the `/ega/skel/inbox` folder in the container `ega_inbox` and the source code

https://github.com/NBISweden/LocalEGA/blob/docker/docker/images/inbox/ega_homedir.sh#L15-16

**Comment by nanjiangshu** [comment]
Merge to master. However, the folder `inbox` still does not exist under `/ega/inbox/userID` after user creation

**Pull request merged**
