### PR TITLE
Change scenarios numeration naming and fix indentation

### PR DESCRIPTION
**Pull request by dtitov**
In accordance with https://github.com/NBISweden/LocalEGA/wiki/Testing-LocalEGA
Authentication -> A.*
Uploading -> U.*
Data-In -> I.*
Data-Out -> O.*

### CODE REVIEW

**Comment by silverdaz** [comment]
Where are the `O.*`s ?

**Comment by dtitov** [comment]
Not there yet, but they'll be.

**Comment by silverdaz** [comment]
But then, why the PR now? Do you need it to move on for another task?

**Comment by dtitov** [comment]
Well, I don't _need_ it, but I _want_ it there because I believe that current naming is a bit confusing. That's why I renamed existing scenarios (to `A`, `U` and `I`) and mentioned a naming for future scenarios (`O`). When I implement `O`-scenarios - I'll make another PR. But it may happen not so soon and since I don't want to postpone this renaming - here we go.

Anyway, I didn't want to distract you, that's why I've asked Johan to review and merge this one.

**Pull request merged**
