### PR TITLE
Listing inbox files

### PR DESCRIPTION
**Pull request by silverdaz**
**Purpose:**
When a file is uploaded to an inbox, a message is sent to CentralEGA's broker with the username and the file path. (Later, we'll even add the checksums. That would be a tremendous help for the helpdesk according to Mauricio).

**Reason:**
We might have directories with _maaaaaany_ files and a `ls` on some REST call would take forever. And we don't need to redo that on each call either! We need to pre-compute the inbox list and cache it. Instead of caching locally, which we have no use for, we send a message to CentralEGA about that file (via a shovel from the local broker).

**Implementation:**
We use a FUSE file system, that simply forwards all requests to the underlying file system but adds a hook when files are closed (and only after they are opened for creation or truncated, otherwise, simply reading the file would trigger a message to CEGA).
We have a FUSE mountpoint for each user, instead of _one_ for all users. That makes the implementation concurrent.
The FUSE program sends a message to the local broker exchange, which gets forwarded to CentralEGA by a shovel.
When an SFTP connection is encountered, we mount the FUSE inbox for the given user and chroot into it. The user sees only `/` (not `/inbox` anymore). On a disconnect, nothing happens and a cron job runs every 5min to unmount and clean up if necessary.

### CODE REVIEW

**Comment by silverdaz** [comment]
PR updated with checksum and file sizes. That's what Mauricio and Oscar wished.

**Comment by silverdaz** [comment]
This PR solves #225 too.

**Comment by silverdaz** [comment]
Note: This PR reduces the number of connections to Central EGA:

* One for the federated queue and
* one for the shovel to answer back for all routing keys (instead of one shovel per routing key)

**Comment by dtitov** [comment]
LGTM, I can play with two commented tests in another PR.

**Pull request merged**
