### PR TITLE
Bootstrap the docker version

### PR DESCRIPTION
**Pull request by silverdaz**
I tried that on my machine, in the [REPO]/docker folder

1) `rm -rf .env*`
2) `docker run --rm -it -v ${PWD}/bootstrap:/ega nbis/ega:worker /ega/generate.sh -f`
3) `docker-compose up -d`
4) `sftp -P 2222 john@localhost` and some password... it worked

The passwords are _all_ randomly generated.
They are in `bootstrap/private/.trace`

Can you please try to ingest a file, and tell me if it worked, maybe there is a problem with the keys or some certificate...
But the fake CentralEGA containers work.

### CODE REVIEW

**Comment by dtitov** [comment]
Good job! Haven't performed uploading and ingestion yet (will try tomorrow), but at least system is starting up, all services are running, front-end is available and `sftp` works.

I have some comments though:
- Shouldn't we run `populate.sh` in Docker as well? I mean it's runnable as script on *nix (Linux, Mac OS, etc.), but it might be a problem for developers on Windows. 
- Can we also parametrize `entrypoints` folder location in `ega.yml`? As it was for `src` location. I need it to be flexible for Jenkins/OpenStack setup.
- I **definitely** don't like the idea of pulling sources in entrypoint-scripts instead of mounting local `src` folder as it was before. Imagine that you want to run some particular "version" of LocalEGA. You clone this version and run it. But it appears that scripts are cloning the newest version inside (which also can be broken in addition). Also it breaks any chance of setting up CI, because during the build of some particular commit there can be done (theoretically) some more commits. And instead of validating this particular commit Jenkins will validate the most recent, which is wrong.

**Comment by silverdaz** [comment]
Good. I hope it helped. I answer your comments:

**Point 1**: The reason I separated the populate script is because the paths were all wrong in the docker container (compared to the host machine where the .env files should be). It's fixable, but we can worry about windows users later.
**Point 2**: Sure. See the last added commit, I added an extra flag to the populate script.
**Point 3**: no need, you can use point 2 to do it. You said: ```Imagine that you want to run some particular "version" of LocalEGA. You clone this version and run it```, so, adjust the entrypoints as you see fit in a cloned folder. Go for `git clone -b <branchyouwant>` or `git clone ...; git checkout <commityouwant>`, that'll do it.

**Comment by silverdaz** [comment]
**Note**: once this is merged, there will be an extra commit (and PR) to switch back to `git clone <repo>` and not `git clone -b docker <repo>`.

That's what I did with the Openstack deployment on the terraform branch.

**Comment by dtitov** [comment]
Thanks for configurable path of entrypoints, but I still disagree about cloning the sources. I got you explanation, but it has two downsides:
- One will need to perform some extra manual step to run **this specific revision** (or tag) he has already cloned. Why? And Jenkins will also need to adjust entrypoints on each triggered build to work with **this specific revision** and not with something that was pushed/merged in between.
- What will happen when repo will be moved or renamed? Or when GitHub will have maintenance or downtime? 

I strongly believe that once you have cloned sources you should not depend on cloning it anymore. That's why the previous approach with mounting local `src` folder was way better.

**Comment by silverdaz** [comment]
The previous approach gives errors. This one doesn't.

**Comment by dtitov** [comment]
Could you be more specific about errors with previous approach?

And I described the errors which can appear with new approach above (unless you edit entrypoints manually, which, I believe, is not a good way of doing things). 

Here's one more, if you want: it's a major vulnerability. Once hacker gets access to the LocalEGA GitHub repo he will potentially get access to all deployments as he will be able to commit any code he want and some LocalEGA deployments may pick-up this code if they are being restarted at the moment. So once this repo is compromised - all the production deployments are compromised. It's basically a security bottleneck.

**Comment by silverdaz** [comment]
Pulling from github is only for testing.
We are not at the production level now.
Don't worry about an attacker getting into Github for the moment.

**Comment by viklund** [comment]
I agree with @dtitov regarding the "git clone" issue, it will be very difficult to run the CI environment with this setup.

I don't care about the security issue, because I do not think anyone should deploy the code from github automatically into production.

What do you say about we merge this now and @dtitov makes a new PR to remove the `git clone` step inside of the entrypoint?

**Comment by silverdaz** [comment]
It is now reverted to mounting the source code into the containers.

If this doesn't give you any issue, then good, go on with the other tasks.
In the meantime, I'll investigate the issues I got, and solve them in other way. (It has to do with a conflict with pip install and setup running in the same shared folder between containers with the make install from the auth code)

**Pull request merged**
