### PR TITLE
Update Kube/Openshift configs

### PR DESCRIPTION
**Pull request by blankdots**
Some of the updates related to Kube/Openshift:
* generating `key.ini.enc` encrypted keys for Kubernetes updated to PR #324 ;
* re-factored the python script for Kubernetes deployment;
* Fixed PostgreSQL Openshift deployment;
* Added Inbox Openshift specific pod config;
* other small updates.

Fix `cryptography` version, in images bootstrap, missed by PR #330

### CODE REVIEW

**Comment by silverdaz** [comment]
Could the Postgres updates be brought to the main branch (and some other deployments)?

It seems to add some rules about how the database tables are owned and accessible by different users. In other words, it possibly brings a bit of security to the database.
So, maybe interesting to bring it into the development and not only for kubernetes deployment?

As a side note: if this is specific to Kubernetes (and Finland), maybe it is time to separate that code into its own repo, and let CSC manage that latter repo?

**Comment by silverdaz** [comment]
Which issue does this PR solve? Click the "Connect with an issue" button, please, and select one.

**Comment by blankdots** [comment]
> Which issue does this PR solve? Click the "Connect with an issue" button, please, and select one.

It solves two, actually an update related to work that  has been done for issue #272 namely PR #324 and a Sprint Goal "Testing in Rahti/ a.k.a. Openshift multi tenant environment", and several bugs found along the way, and one miss by PR #330 
I will write an issue for the sprint goal.

> Could the Postgres updates be brought to the main branch (and some other deployments)?

They could, considering this involved experimenting with UUIDs while there is `pgcrypto`, also looked into other options such as `uuid-ossp` or https://rob.conery.io/2014/05/28/a-better-id-generator-for-postgresql/ for alternatives.

Other question will be answered in slack channel.

**Review by juhtornr — APPROVED** [review]
There are actually three different (but related) things in this PR:

 - Updated Kube/Openshift configs
 - SFTP client for testing in Openshift 
 - Encryption key changes in Kubernetes deployment (and according changes in tests)

All of these things was discussed but in the future it would be easier to follow if PRs would be smaller and connected to specific issue.

**Pull request merged**
