### PR TITLE
Add Minio implementation of S3 to bootstrapping

### PR DESCRIPTION
**Pull request by dtitov**
Description: https://minio.io/
Tested with Python client: https://github.com/minio/minio-py

### CODE REVIEW

**Comment by dtitov** [comment]
Also successfully tested with official client S3 SDK for Python from Amazon: https://aws.amazon.com/sdk-for-python/

**Comment by silverdaz** [comment]
Yes, `boto3` was what we had in mind already.
Good job, if you got in running.
I let Juha review it.

**Comment by dtitov** [comment]
Thank you. 

Well, it's not there yet :) This PR solves the next sprint goal: `Provide a mock of S3 interface for Docker`. So now we have it.

Then there's another goal that sounds: `Create a plan for implementing S3 interface`. I think it's more related to what you mentioned: make it possible to use S3-storage as a back-end for our vault (at least to plan it).

**Comment by silverdaz** [comment]
Oh I see.
That's not how I imagined it, but I approve those changes.
It's a good start for the rest.

**Comment by juhtornr** [comment]
Works like a charm:

```
[tornroos:...LocalEGA/deployments/docker]$ docker-compose up -d s3-swe1                                (dev✱) 
ega-s3-swe1 is up-to-date
[tornroos:...LocalEGA/deployments/docker]$ docker-compose ps | grep s3-swe1                            (dev✱) 
ega-s3-swe1              /usr/bin/docker-entrypoint ...   Up         0.0.0.0:9001->9000/tcp
[tornroos:...LocalEGA/deployments/docker]$ cat test.py                                                 (dev✱) 
# Import Minio library.
from minio import Minio
from minio.error import (ResponseError, BucketAlreadyOwnedByYou,
                         BucketAlreadyExists)

# Initialize minioClient with an endpoint and access/secret keys.
minioClient = Minio('localhost:9001',
                    access_key='jEbJpjGR6yKYnCgX',
                    secret_key='r9cDqgBLC7jjfGu4V6e19sEoKqcLRPab',
                    secure=False)

# Make a bucket with the make_bucket API call.
try:
       minioClient.make_bucket("lega", location="us-east-1")
except BucketAlreadyOwnedByYou as err:
       pass
except BucketAlreadyExists as err:
       pass
except ResponseError as err:
       raise
else:
        # Put an object 'pumaserver_debug.log' with contents from 'pumaserver_debug.log'.
        try:
               minioClient.fput_object('lega', 'test-file', '/tmp/test-file')
        except ResponseError as err:
               print(err)
[tornroos:...LocalEGA/deployments/docker]$ cat > /tmp/test-file                                        (dev✱) 
foobar
[tornroos:...LocalEGA/deployments/docker]$ python3 test.py                                             (dev✱) 
[tornroos:...LocalEGA/deployments/docker]$ docker-compose exec s3-swe1 ls /data/lega/test-file         (dev✱) 
/data/lega/test-file
[tornroos:...LocalEGA/deployments/docker]$ docker-compose exec s3-swe1 cat /data/lega/test-file        (dev✱) 
foobar
```

**Comment by silverdaz** [comment]
Then it's only about updating `vault.py`, and injecting the s3 parameters in the `conf.ini` file.

**Pull request merged**
