### PR TITLE
NSS big commit for review

### PR DESCRIPTION
**Pull request by viklund**
This is some C code intended to run as a PAM module in linux. This will be run as root. The point of it is to enable us to read usernames and passwords from at postgresql database instead of using the standard linux user handling systems.

### CODE REVIEW

**Comment by silverdaz** [comment]
`libpq-fe.h` comes with the postgres libs

**Comment by kusalananda** [comment]
So it does. I finally found it in `libpq-dev` on Ubuntu.  This package also comes with `pg_config` which gives you the opportunity to use `pg_config --cflags` and `pg_config --ldflags` in the Makefile instead of hardcoding e.g. the include path (I had to change it by hand).

**Comment by silverdaz** [comment]
Do you think it's a good idea to use `pg_config`? I have seen it done in other unrelated Makefiles, but maybe we should go the `libtool` way? 

I don't think I have it in me to package that thing nicely. All I want is to make it work in _one_ environment (currently CentOS7)...

Is that important?

**Comment by silverdaz** [comment]
Note: I like the idea to use `pg_config`. Just commenting on how much work to put into this...

**Comment by kusalananda** [comment]
No, it's not important. If the Makefile picks up all the right headers and libraries, then by all means continue as you have done. I would, however, check the `CFLAGS` and `LDFLAGS` in the Makefile against the `pg_config` output for those variables. When I had a look it was quite different (_but it was on Ubuntu_). I _did_ approve the PR...

**Pull request closed without merging**
