### PR TITLE
Create requirements.txt for SNYK

### PR DESCRIPTION
**Pull request by jhagberg**
Using SNYK to automate security test requires a manifest file. 
https://support.snyk.io/getting-started/languages-support
Create this file from the information in setup.py

### CODE REVIEW

**Comment by silverdaz** [comment]
If so, then I need to change the entrypoints (and terraform boot scripts) to do a `pip install -r` in order to first install the dependencies.

I prefered to have it done by the setup.py.

**Comment by jhagberg** [comment]
No it is not necessary just if we want to run snyk test to see if we have any know vulnerability. 
If you can point me to the new standard maybe I can open a request for SNYK to handle it the new way instead.

**Comment by jhagberg** [comment]
There is no need to change everything just add a extra file so that SNYK can run. It is just for SNYK

**Comment by silverdaz** [comment]
ok, then I approve the request. But I'm not fond of having the same information in many places. If we make a change, we'll have to apply it everywhere, and we might miss one place.

**Comment by silverdaz** [comment]
Create an EPIC for this type of code changes. I suggest: `Code Quality`

**Comment by jhagberg** [comment]
I agree but this is just a workaround, for now, We could probably delete this later and the SNYK scans might not be useful.

**Comment by silverdaz** [comment]
I agree Nanjiang. We are already reading the README file in the setup.py.
I just like having one file and not too many.
But it's not a big deal, and easy to revert if we don't like it.

**Pull request merged**
